# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Publish python distribution 📦 to PyPI

on:
  # Publish wheels to pypi on release
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      force:
        description: "Force build and ignore cache"
        required: false
        default: "false"
  
permissions:
  contents: read

jobs:
  build:
    name: Call Python Wheels Workflow
    steps:
      - name: Build python-wheels
        uses: ./.github/workflows/python-wheels.yml
        with:
          force: ${{ inputs.force || 'false' }}

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/openexr

    permissions:
      id-token: write

    steps:

    - name: Restore Linux Build Cache
      uses: actions/cache@v4
      with:
        path: dist
        key: python-build-${{ github.sha }}-ubuntu-latest
    - name: Restore macOS Build Cache
      uses: actions/cache@v4
      with:
        path: dist
        key: python-build-${{ github.sha }}-macos-latest
    - name: Restore Windows Build Cache
      uses: actions/cache@v4
      with:
        path: dist
        key: python-build-${{ github.sha }}-windows-latest
    - name: show dir
      shell: bash
      run: |
        ls -al dist
    # - name: Publish distribution 📦 to PyPI
    #   uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc # v1.12.2
